import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { success, info, warn, error } from '../utils/output';

// --- Command and subcommand definitions for completion scripts ---

const TOP_LEVEL_COMMANDS = [
  'auth',
  'config',
  'account',
  'campaigns',
  'adsets',
  'ads',
  'creatives',
  'insights',
  'images',
  'deploy',
  'projects',
  'monitor',
  'generate',
  'audiences',
  'labels',
  'completions',
  'bulk',
];

const SUBCOMMANDS: Record<string, string[]> = {
  auth: ['login', 'logout', 'status', 'token'],
  config: ['get', 'set', 'list', 'reset'],
  account: ['info', 'list'],
  campaigns: ['list', 'get', 'create', 'update', 'pause', 'resume', 'archive', 'delete', 'copy'],
  adsets: ['list', 'get', 'create', 'update', 'pause', 'resume', 'archive', 'delete', 'copy'],
  ads: ['list', 'get', 'create', 'update', 'pause', 'resume', 'archive', 'delete', 'copy'],
  creatives: ['list', 'get', 'create', 'delete'],
  insights: ['account', 'campaign', 'adset', 'ad'],
  images: ['list', 'upload', 'delete'],
  deploy: ['create', 'status', 'preview'],
  projects: ['list', 'get', 'create', 'delete'],
  monitor: ['start', 'status', 'stop'],
  generate: ['ad', 'copy', 'headline', 'image'],
  audiences: ['list', 'get', 'create', 'delete', 'share'],
  labels: ['list', 'get', 'create', 'delete', 'assign', 'remove'],
  completions: ['bash', 'zsh', 'fish', 'install'],
  bulk: ['pause', 'resume', 'delete', 'update'],
};

const GLOBAL_OPTIONS = ['--json', '--account-id', '--fields', '--limit', '--help', '--version'];

// --- Bash completion script ---

function generateBashScript(): string {
  const subcommandCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => `    ${cmd})\n      COMPREPLY=( $(compgen -W "${subs.join(' ')}" -- \${cur}) )\n      return 0\n      ;;`)
    .join('\n');

  return `#!/bin/bash
# adpilot bash completion
# Generated by: adpilot completions bash
# Install: adpilot completions bash >> ~/.bashrc && source ~/.bashrc

_adpilot_completions() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  words=("\${COMP_WORDS[@]}")
  cword=$COMP_CWORD

  # Top-level commands
  local commands="${TOP_LEVEL_COMMANDS.join(' ')}"

  # Global options
  local global_options="${GLOBAL_OPTIONS.join(' ')}"

  # If completing an option (starts with -)
  if [[ \${cur} == -* ]]; then
    COMPREPLY=( $(compgen -W "\${global_options}" -- \${cur}) )
    return 0
  fi

  # Subcommand completions based on previous word
  case "\${prev}" in
    adpilot)
      COMPREPLY=( $(compgen -W "\${commands}" -- \${cur}) )
      return 0
      ;;
${subcommandCases}
  esac

  # If we're at position 1, complete commands
  if [[ \${cword} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- \${cur}) )
    return 0
  fi

  # Default: try to complete subcommands for the command at position 1
  local cmd="\${words[1]}"
  case "\${cmd}" in
${subcommandCases}
  esac

  return 0
}

complete -F _adpilot_completions adpilot
`;
}

// --- Zsh completion script ---

function generateZshScript(): string {
  const subcommandCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => {
      const subsStr = subs.map(s => `'${s}:${s} ${cmd}'`).join(' ');
      return `      ${cmd})\n        local -a ${cmd}_commands\n        ${cmd}_commands=(${subsStr})\n        _describe '${cmd} commands' ${cmd}_commands\n        ;;`;
    })
    .join('\n');

  return `#compdef adpilot
# adpilot zsh completion
# Generated by: adpilot completions zsh
# Install: adpilot completions zsh > ~/.zsh/completions/_adpilot
# Then add to .zshrc: fpath=(~/.zsh/completions $fpath) && autoload -Uz compinit && compinit

_adpilot() {
  local -a commands
  commands=(
${TOP_LEVEL_COMMANDS.map(c => `    '${c}:Manage ${c}'`).join('\n')}
  )

  _arguments -C \\
    '--json[Output as JSON]' \\
    '--account-id[Ad account ID]:account id:' \\
    '--fields[Comma-separated fields]:fields:' \\
    '--limit[Max results]:limit:' \\
    '--help[Show help]' \\
    '--version[Show version]' \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'adpilot commands' commands
      ;;
    args)
      case $words[1] in
${subcommandCases}
      esac
      ;;
  esac
}

_adpilot "$@"
`;
}

// --- Fish completion script ---

function generateFishScript(): string {
  const lines = [
    '# adpilot fish completion',
    '# Generated by: adpilot completions fish',
    '# Install: adpilot completions fish > ~/.config/fish/completions/adpilot.fish',
    '',
    '# Disable file completions by default',
    'complete -c adpilot -f',
    '',
    '# Top-level commands',
  ];

  for (const cmd of TOP_LEVEL_COMMANDS) {
    lines.push(
      `complete -c adpilot -n '__fish_use_subcommand' -a '${cmd}' -d 'Manage ${cmd}'`
    );
  }

  lines.push('');
  lines.push('# Subcommands');

  for (const [cmd, subs] of Object.entries(SUBCOMMANDS)) {
    for (const sub of subs) {
      lines.push(
        `complete -c adpilot -n '__fish_seen_subcommand_from ${cmd}' -a '${sub}' -d '${sub}'`
      );
    }
  }

  lines.push('');
  lines.push('# Global options');
  lines.push(`complete -c adpilot -l json -d 'Output as JSON'`);
  lines.push(`complete -c adpilot -l account-id -d 'Ad account ID' -r`);
  lines.push(`complete -c adpilot -l fields -d 'Comma-separated fields' -r`);
  lines.push(`complete -c adpilot -l limit -d 'Max results' -r`);
  lines.push('');

  return lines.join('\n');
}

// --- Shell detection ---

function detectShell(): 'bash' | 'zsh' | 'fish' | 'unknown' {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('bash')) return 'bash';
  if (shell.includes('fish')) return 'fish';
  return 'unknown';
}

// --- Install logic ---

function installCompletions(): void {
  const shell = detectShell();

  if (shell === 'unknown') {
    error('Could not detect your shell. Please install completions manually:');
    info('  adpilot completions bash >> ~/.bashrc');
    info('  adpilot completions zsh  > ~/.zsh/completions/_adpilot');
    info('  adpilot completions fish > ~/.config/fish/completions/adpilot.fish');
    return;
  }

  switch (shell) {
    case 'bash': {
      const bashrcPath = path.join(os.homedir(), '.bashrc');
      const marker = '# adpilot bash completion';
      const existing = fs.existsSync(bashrcPath) ? fs.readFileSync(bashrcPath, 'utf-8') : '';

      if (existing.includes(marker)) {
        warn('Bash completions already installed in ~/.bashrc');
        info('To reinstall, remove the existing adpilot completion block and run again.');
        return;
      }

      const script = generateBashScript();
      fs.appendFileSync(bashrcPath, '\n' + script + '\n');
      success(`Bash completions installed to ${bashrcPath}`);
      info('Run: source ~/.bashrc   (or open a new terminal)');
      break;
    }

    case 'zsh': {
      const completionDir = path.join(os.homedir(), '.zsh', 'completions');
      const completionFile = path.join(completionDir, '_adpilot');

      fs.mkdirSync(completionDir, { recursive: true });
      fs.writeFileSync(completionFile, generateZshScript());

      success(`Zsh completions installed to ${completionFile}`);
      info('Ensure your .zshrc contains:');
      info('  fpath=(~/.zsh/completions $fpath)');
      info('  autoload -Uz compinit && compinit');
      info('Then run: source ~/.zshrc   (or open a new terminal)');
      break;
    }

    case 'fish': {
      const fishDir = path.join(os.homedir(), '.config', 'fish', 'completions');
      const fishFile = path.join(fishDir, 'adpilot.fish');

      fs.mkdirSync(fishDir, { recursive: true });
      fs.writeFileSync(fishFile, generateFishScript());

      success(`Fish completions installed to ${fishFile}`);
      info('Completions will be available in new fish sessions.');
      break;
    }
  }
}

// --- Register commands ---

export function registerCompletionCommands(program: Command): void {
  const completions = program
    .command('completions')
    .description('Generate shell completion scripts');

  completions
    .command('bash')
    .description('Output bash completion script')
    .action(() => {
      process.stdout.write(generateBashScript());
    });

  completions
    .command('zsh')
    .description('Output zsh completion script')
    .action(() => {
      process.stdout.write(generateZshScript());
    });

  completions
    .command('fish')
    .description('Output fish completion script')
    .action(() => {
      process.stdout.write(generateFishScript());
    });

  completions
    .command('install')
    .description('Auto-detect shell and install completion script')
    .action(() => {
      installCompletions();
    });
}
